# Generated by Django 6.0.6 on 2026-07-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('booking_time', models.DateField()),
                ('contact', models.IntegerField()),
                ('Events', models.CharField(choices=[('wedding', 'wedding'), ('Birthday', 'Birthday'), ('Ceremony', 'Ceremony'), ('Otheres', 'Others')], default='wedding', null=True)),
                ('Booking_stauts', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', null=True)),
                ('number_of_guest', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('esewa', 'esewa')], default='cash', null=True)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'Booking',
                'unique_together': {('booking_time',)},
            },
        ),
    ]
