# Generated by Django 6.0.6 on 2026-07-07 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingmodel',
            options={'ordering': ['-booking_time']},
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='Booking_stauts',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='Events',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='event',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('ceremony', 'Ceremony'), ('others', 'Others')], default='wedding', null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'Esewa')], default='cash', null=True),
        ),
    ]
