# Generated by Django 6.0.6 on 2026-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0002_alter_bookingmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='order_code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='payment_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
