# Generated by Django 6.0.6 on 2026-07-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0003_bookingmodel_order_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='order_code',
            field=models.CharField(max_length=10),
        ),
    ]
