# Generated by Codex on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0004_alter_bookingmodel_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('unpaid', 'Unpaid'),
                    ('pending', 'Pending'),
                    ('paid', 'Paid'),
                    ('failed', 'Failed'),
                ],
                default='unpaid',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='order_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
