# Generated by Django 6.0.6 on 2026-07-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0005_esewa_payment_status_and_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='order_code',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='payment_response',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='transaction_id',
        ),
    ]
