# Generated by Django 6.0.6 on 2026-07-02 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingPalace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Name of the wedding palace', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name', max_length=220, unique=True)),
                ('address', models.TextField(help_text='Full address')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('location', models.URLField(help_text='please provide the url of the google map  ')),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests')),
                ('parking_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('NPR', 'NPR (Nepalese Rupee)'), ('USD', 'USD (US Dollar)'), ('INR', 'INR (Indian Rupee)')], default='NPR', max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(help_text='Overview and highlights')),
                ('cover_image', models.ImageField(blank=True, help_text='Main/cover image of the palace', null=True, upload_to='palace_covers/')),
                ('video', models.FileField(blank=True, help_text='Main video of your palace', null=True, upload_to='palace_video/')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization info',
            },
        ),
    ]
