# Generated by Django 6.0.6 on 2026-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingpalace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
