# Generated by Django 6.0.6 on 2026-07-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_content_delete_blogsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(blank=True, help_text='upload here your content', null=True),
        ),
    ]
