# Generated by Django 6.0.6 on 2026-07-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
    ]
