# Generated by Django 6.0.6 on 2026-07-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0005_alter_user_created_at'),
        ('app_accounts', '0007_alter_user_username'),
    ]

    operations = [
    ]
