# Generated by Django 6.0.6 on 2026-07-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
