# Generated by Django 6.0.6 on 2026-07-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0008_merge_20260707_1256'),
        ('app_accounts', '0010_alter_user_managers'),
    ]

    operations = [
    ]
