# Generated by Django 6.0.6 on 2026-07-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0011_merge_20260712_1604'),
        ('app_accounts', '0012_alter_user_managers'),
    ]

    operations = [
    ]
